### ISSUE TITLE
Add hardware ID to WS LoggingEnvironment (notes)

### ISSUE THREAD

**Issue by mbrit** [onovotny/MetroLog#24]
http://digitalmindignition.wordpress.com/2012/10/12/finding-the-device-id-in-windows-8/
http://www.wadewegner.com/2012/09/getting-the-application-id-and-hardware-id-in-windows-store-applications/

private string GetHardwareId()
{
var token = HardwareIdentification.GetPackageSpecificToken(null);
var hardwareId = token.Id;
var dataReader = Windows.Storage.Streams.DataReader.FromBuffer(hardwareId);

byte[] bytes = new byte[hardwareId.Length];
dataReader.ReadBytes(bytes);

return BitConverter.ToString(bytes);
}

**Comment by onovotny** [comment]
Closing as I'm not sure how useful this is. It's randomized per app and per user. If there's a need for this, we can re open and implement.
