### ISSUE TITLE
Feature request: LogManagerFactory.DefaultConfiguration.AllTargets

### ISSUE THREAD

**Issue by topsites** [onovotny/MetroLog#44]
It would be nice to have a method like
LogManagerFactory.DefaultConfiguration.AllTargets

which would basically NLog's method for internal GetTargets; or perhaps event having that as public.

Reason: I would like to gracefully flush all logs at shutdown; so it makes sense to find all the targets from configuration and issuing flush command one at a time to ensure no multiple writing problems.

PS: For Mono, suggested profile to use is 158;

**Comment by onovotny** [comment]
This exists on the LoggingConfiguration as `GetTargets()`
