### ISSUE TITLE
Change LogLevel at runtime

### ISSUE THREAD

**Issue by furier** [onovotny/MetroLog#45]
Change `LogLevel` at runtime without requiring an application restart.

In the `App.xaml.cs` file I initialize the targets I want my logger to have as such:

    LogManagerFactory.DefaultConfiguration.AddTarget(LogLevel.Trace, LogLevel.Fatal, 
        new FileStreamingTarget(new SingleLineLayout()));

As far as I have understood, this is the only place you set min and max `LogLevel` for any given target.

As `LogManagerFactory.DefaultConfiguration` doesn't let you list, get or remove any previously added targets, I cant change a targets `LogLevel` configurations at runtime.
Neither can I remove it and just add a new one with the new configurations.

**Comment by JamesNK** [comment]
Why was this closed? I would like to change the log level at runtime and I don't see a way to do that.

Using private reflection isn't a good solution.

**Comment by lassana** [comment]
Bump. Any updates on this?

**Comment by inxomnyaa** [comment]
Bump - just also got this.
```

namespace NameSpaceOfApp
{
    sealed partial class App : Application
    {

        private ILogger log = LogManagerFactory.DefaultLogManager.GetLogger<App>();
        public App()
        {
#if DEBUG
            LogManagerFactory.DefaultConfiguration.AddTarget(LogLevel.Trace, LogLevel.Fatal, new StreamingFileTarget());
#else
            LogManagerFactory.DefaultConfiguration.AddTarget(LogLevel.Error, LogLevel.Fatal, new StreamingFileTarget());
#endif

            GlobalCrashHandler.Configure();
[...]
```

As shown in the example here: https://talkitbr.com/2015/06/11/adicionando-logs-em-universal-apps/
