### ISSUE TITLE
As a developer I want to be able to access all logs via MetroLog API.

### ISSUE THREAD

**Issue by kosiek** [onovotny/MetroLog#60]
There are some things I can't test properly (connected to how program works in real conditions, dettached from debugging mode) and before implementing MetroLog I was using file with the content that was bound to XAML interface so I knew on the device how was it working. But I think it would be better if MetroLog gave me a way to get all loged messages as a List<ILogEntry> or formatted string.

**Comment by thomasgalliker** [comment]
Hi kosiek. Don't know if I understand you correctly: Couldn't you just create a logger target that writes each log message to an in-memory list (which you can easily access)?

**Comment by kosiek** [comment]
Hi,

Thanks for your reply. Is there any documentation concerning the usage of that solution? If I could write the messages to the structure that would be added to the ICollection, that would suit my needs.

**Comment by thomasgalliker** [comment]
// Create a new LoggingConfiguration and add your custom target (e.g. CollectionTarget, see below)
            var config = new LoggingConfiguration();
            var collectionTarget = new CollectionTarget(new SingleLineLayout());
            config.AddTarget(LogLevel.Debug, LogLevel.Error, collectionTarget);
            var logManager = LogManagerFactory.CreateLogManager(config);
            
// Create a named logger instance and write some sample log message to it.
            var testLogger = logManager.GetLogger("TestLogger");
            testLogger.Debug("Sample message");

// Retrieve all logged entries. It's up to you what you want to do when a new log entry arrives (e.g. raising an event or doing other fancy things...
            collectionTarget.GetLogEntries();

// CollectionTarget:
   public class CollectionTarget : SyncTarget
    {
        private readonly ICollection<LogEventInfo> logEntries;

        public CollectionTarget(Layout layout)
            : base(layout)
        {
            this.logEntries = new Collection<LogEventInfo>();
        }

        protected override void Write(LogWriteContext context, LogEventInfo entry)
        {
            this.logEntries.Add(entry);
        }

        public ICollection<LogEventInfo> GetLogEntries()
        {
            return this.logEntries;
        }
    }

**Comment by thomasgalliker** [comment]
Problem solved?

**Comment by kosiek** [comment]
Yes, I think it solves the issue for me. Thank you for your help. :)
