### ISSUE TITLE
Question: Metrolog in PCL- possible to append log entries?

### ISSUE THREAD

**Issue by uwaka** [onovotny/MetroLog#64]
Hi
I'm trying to implement Metrolog in PCL, and have some of my methods within the PCL project write to log. I couldn't find an inherent PCL specific Target but then I saw Viktor Hofer's Portable File Target so I've grabbed it and seems to be what i needed.
Anyway, my question is regarding the actual logs creations- is there a way to configure Metrolog to append log entries instead of creating new flies on the fly?

**Comment by onovotny** [comment]
MetroLog will append if it's the same log filename and it's configured to append. This is the default behavior. Also by default it puts the date in the filename so it'll create a new file per day.
