### ISSUE TITLE
SQLite with Windows 10 Universal app?

### ISSUE THREAD

**Issue by K232** [onovotny/MetroLog#73]
Hi all,
do you have an example how to use MetroLog with recommended SQLite in a Windows 10 Universal App? I tried logging to a file which works fine but could not pass the test of Windows Certification Kit :-(
Thanks in advance!

**Comment by onovotny** [comment]
What kind of WACK errors were you getting and in what configuration?

MetroLog is used in numerous Win10 universal apps w/o issues.

**Comment by K232** [comment]
The following tests fail:

-----
FAILED
    App prelaunch

    Error Found: The app prelaunch validation detected the following errors:
        The app failed prelaunch test - 
    Impact if not fixed: The app will take a longer time to launch, even when prelaunch is enabled.
    How to fix: In the OnLaunched method implementation of the app, ensure you handle the LaunchActivatedEventArgs.PreLaunch option to be prelaunch event aware.


FAILED
    Crashes and hangs

    Error Found: The crashes and hangs test detected the following errors:
        Executable  was detected by Windows Error Reporting and experienced a crash or hang.
        Application  was detected by Windows Error Reporting and experienced a crash or hang.
        Crash dump file  was created by Windows Error Reporting and provides additional information.
    Impact if not fixed: An app that stops responding or crashes can cause data loss and is a poor user experience.
    How to fix: Investigate and debug the app to identify and fix the problem. 

-----

It's a Win10 Universal App and in my app.xaml.cs I only added these lines:

   protected override void OnLaunched(LaunchActivatedEventArgs e)
        {
            var configuration = new MetroLog.LoggingConfiguration();
            configuration.AddTarget(MetroLog.LogLevel.Trace, MetroLog.LogLevel.Fatal, new MetroLog.Targets.FileStreamingTarget());
            configuration.IsEnabled = true;
            MetroLog.LogManagerFactory.DefaultConfiguration = configuration;
            var logger = MetroLog.LogManagerFactory.DefaultLogManager.GetLogger<App>();
            logger.Info("---------------------------------------Starting Application.---------------------------------------");
          

As soon as I remove all the lines, everything works fine and WACK finishes without problems. I have keep the lines in app.xaml.cs the application still runs file and the logfile is written as expected, but WACK always fails...

**Comment by K232** [comment]
Any ideas?

**Comment by clairernovotny** [comment]
This seems to be an issue with pre-launch but I have not had time to look into this yet specifically.

**Comment by K232** [comment]
No problem. Is there somewhere an example how to use SQLite in Universal Windows 10 App? I already tried to use it but was not successfull.
