### ISSUE TITLE
UWP: StreamingFileTarget jumps threads and fails with UnauthorizedAccessException

### ISSUE THREAD

**Issue by jesperll** [onovotny/MetroLog#74]
version 1.0.0-rc1

```
static App()
{
    var loggingConfiguration = new LoggingConfiguration();
    loggingConfiguration.AddTarget(LogLevel.Trace, LogLevel.Fatal, new StreamingFileTarget());
    LogManagerFactory.DefaultConfiguration = loggingConfiguration;
    var log = LogManagerFactory.DefaultLogManager.GetLogger<App>();
    for (int i = 0; i < 100; i++)
    {
        log.Trace("What thread am I?");
    }
}
```

The above code will fail after writing one line to the log file and just throw UnobservedTaskException for the rest

I tried inheriting from StreamingfileTarget and returning a cached stream in GetWritableStreamForFile

This prevents the app from crashing but the thread info in the log is all out of sync with the actual thread calling log.Trace

> 2|2016-01-29T11:36:35.4920094+00:00|TRACE|4|App|What thread am I?
> 3|2016-01-29T11:36:35.6304338+00:00|TRACE|6|App|What thread am I?
> 4|2016-01-29T11:36:35.6359357+00:00|TRACE|6|App|What thread am I?
> 5|2016-01-29T11:36:35.6369347+00:00|TRACE|6|App|What thread am I?
> 6|2016-01-29T11:36:35.6384341+00:00|TRACE|7|App|What thread am I?
> 7|2016-01-29T11:36:35.6399331+00:00|TRACE|7|App|What thread am I?
> 8|2016-01-29T11:36:35.6414339+00:00|TRACE|6|App|What thread am I?
> 9|2016-01-29T11:36:35.6429330+00:00|TRACE|9|App|What thread am I?

By comparison the output in my debug window is

> 2|2016-01-29T11:36:35.4920094+00:00|TRACE|3|App|What thread am I?
> 3|2016-01-29T11:36:35.6304338+00:00|TRACE|3|App|What thread am I?
> 4|2016-01-29T11:36:35.6359357+00:00|TRACE|3|App|What thread am I?
> 5|2016-01-29T11:36:35.6369347+00:00|TRACE|3|App|What thread am I?
> 6|2016-01-29T11:36:35.6384341+00:00|TRACE|3|App|What thread am I?
> 7|2016-01-29T11:36:35.6399331+00:00|TRACE|3|App|What thread am I?
> 8|2016-01-29T11:36:35.6414339+00:00|TRACE|3|App|What thread am I?
> 9|2016-01-29T11:36:35.6429330+00:00|TRACE|3|App|What thread am I?

**Comment by onovotny** [comment]
Just checked in a fix, thanks for reporting this.

**Comment by jesperll** [comment]
Thanks @onovotny. It doesn't crash anymore but I'm still seeing the wrong thread id

All my logging is calling the synchronous methods (which under the hood just call the async ones)

If I write multiple log statements after each other they show up with different ids in the log file but not in the debugger output.

My guess is that Layout.GetFormattedString() in FileTargetBase.WriteAsyncCore should be called before any awaits (especially ones with ConfigureAwait(false) to ensure that the entry is formatted on the original thread
